#.
#Parameters and abilities of VS Clockwork's kinetic mechanisms
[cwkinetics]
	#.
	#.
	#RPM input requirement per Sail attached.
	#Range: > 1
	propellorRPMPerSail = 8
	#.
	#Maximum scan distance of the Ballooner's floodfill algorithm.
	#Range: > 1
	balloonRange = 4096
